### ISSUE TITLE
Vertical alignment is wrong after Windows 11 23H2 Update

### ISSUE THREAD

**Issue by turkeyphant** [zhongyang219/TrafficMonitor#1766]
![image](https://github.com/zhongyang219/TrafficMonitor/assets/8129583/61b37ad8-5a84-4564-8844-a2ec54183020)

After updating to Windows 11 23H2 the taskbar alignment is wrong.

**Comment by turkeyphant** [comment]
It also doesnt respect app icons which can overflow into it:
![image](https://github.com/zhongyang219/TrafficMonitor/assets/8129583/44df442c-5e74-4514-ba45-52d2106f78da)

**Comment by 954-Ivory** [comment]
Me too

**Comment by beekter** [comment]
+1

**Comment by gkcngk** [comment]
Same issue with the display 

![image](https://github.com/zhongyang219/TrafficMonitor/assets/96928780/81a41dc6-ecb0-40a2-8e53-7a1f121796a4)


OS Name	Microsoft Windows 11 Home
Version	10.0.22631 Build 22631

**Comment by Naco** [comment]
> It also doesnt respect app icons which can overflow into it: ![image](https://private-user-images.githubusercontent.com/8129583/299970310-44df442c-5e74-4514-ba45-52d2106f78da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwNjU3NjQsIm5iZiI6MTcwODA2NTQ2NCwicGF0aCI6Ii84MTI5NTgzLzI5OTk3MDMxMC00NGRmNDQyYy01ZTc0LTQ1MTQtYmE0NS01MmQyMTA2Zjc4ZGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTZUMDYzNzQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGZhYWYxNTc1ZjA2NGE0ZTE3OGIyNzhmYTc3NDU4N2Q5ZDdiMTNkM2UzNmYxMTdkNTNmMTI1MTNkMmMxMTA4OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HRJOiWoGbIyPUOE7lbeyIqGU4VbAO57eL1QSFLMN4lY)

Same issue

**Comment by JacekCGN** [comment]
Same Taskbar issue with Windows 11 Version 22H2 (OS Build 22621,3155)

**Comment by iqbalfaaizi** [comment]
+1

**Comment by Patrick-3012** [comment]
Same Proplem 
<img width="344" alt="Screenshot 2024-03-30 231854" src="https://github.com/zhongyang219/TrafficMonitor/assets/89484164/49b0a2a9-7e5a-45cc-8b9c-9295ad79428b">

**Comment by ThomasHawaii** [comment]
Same here ... is there any solution???

**Comment by beekter** [comment]
fixed in 1.85
![image](https://github.com/user-attachments/assets/9517d481-c1c2-481b-85fb-76f6e9a04554)

**Comment by JacekCGN** [comment]
> fixed in 1.85 ![image](https://private-user-images.githubusercontent.com/20529431/375883463-9517d481-c1c2-481b-85fb-76f6e9a04554.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MjE2MjcsIm5iZiI6MTcyODcyMTMyNywicGF0aCI6Ii8yMDUyOTQzMS8zNzU4ODM0NjMtOTUxN2Q0ODEtYzFjMi00ODFiLTg1ZmItNzZmNmU5YTA0NTU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA4MjIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2MDdhNDYyZTVjZTQ3YTNmNTAxMDg4YWJmNzhjMWVlZDU2YmQyNjljNWI1N2E4OGJlNjEyNjJkYjc2YzcyOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XHq-KjU489wfLmAczVjcO99ikoI06v-k1M6yK_UUf8w)

Downloadlink available?

**Comment by Ameer5CT** [comment]
> > fixed in 1.85 ![image](https://private-user-images.githubusercontent.com/20529431/375883463-9517d481-c1c2-481b-85fb-76f6e9a04554.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MjE2MjcsIm5iZiI6MTcyODcyMTMyNywicGF0aCI6Ii8yMDUyOTQzMS8zNzU4ODM0NjMtOTUxN2Q0ODEtYzFjMi00ODFiLTg1ZmItNzZmNmU5YTA0NTU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA4MjIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2MDdhNDYyZTVjZTQ3YTNmNTAxMDg4YWJmNzhjMWVlZDU2YmQyNjljNWI1N2E4OGJlNjEyNjJkYjc2YzcyOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XHq-KjU489wfLmAczVjcO99ikoI06v-k1M6yK_UUf8w)
> 
> Downloadlink for 1.85 available? 

https://github.com/yxyzjuGIT/TrafficMonitor/releases/tag/V1.85

I downloaded it from this fork and it fixed it, There's also a v1.90 but for me that version crashes when I change the text color so I will stick to v1.85

**Comment by zhongyang219** [comment]
This problem has been fixed, please update to the latest version.

**Comment by turkeyphant** [comment]
> This problem has been fixed, please update to the latest version.

Updated to latest version:

![Image](https://github.com/user-attachments/assets/58d4135a-f117-462d-8bcf-e7c3ee8c4701)

Problem still not fixed:

![Image](https://github.com/user-attachments/assets/0f9ab7c3-9641-4c61-a071-cfbe3799d40f)

**Comment by zhongyang219** [comment]
> Problem still not fixed:
> 
> ![Image](https://github.com/user-attachments/assets/0f9ab7c3-9641-4c61-a071-cfbe3799d40f)

This is the limitation of the winsows11 taskbar, I can't fix it.
